### ISSUE TITLE
Allow fields to be excluded from being required

### ISSUE THREAD

**Issue by AjkayAlan** [podhmo/alchemyjsonschema#28]
Good Afternoon!

# My Ask

This is a super neat library that _almost_ meets my needs. The only thing that I am struggling with is that I would like the ability to exclude my primary key from being required in the generated schema.

## The Usecase

I have an API project which uses SqlAlchemy for the database interaction. Currently that API doesn't do any mapping between "domain models" and "database models". So, the JSON schemas that I would give out to API users matches my DB models (so this library works)

## The Problem

My API is a simple CRUD API. The issue I am running into is that the primary key field (id) is marked as required, but that field is database generated. So, my API callers won't provide an id when calling the create route.

This causes a problem, because if I validate their JSON against the generated schema from alchemyjsonschema, it fails validation, when instead I would like it to pass.

## The Solution
Could their be an option flag or something on the factory which does something like `mark_primary_keys_as_required=False` (and defaults to true so it won't be a breaking change)? That way I could do something like:

`SchemaFactory(NoForeignKeyWalker)(Pet, mark_primary_keys_as_required=False)`

That, or move that option to the factory.

A more reusable pattern would be something like a `not_required_fields=id,field2,etc`. Something which allows you to control the required output and override what the actual models would output.

**Comment by podhmo** [comment]
OK, I'll try it later, maybe next weekend

**Comment by podhmo** [comment]
I'll implement it like this (this is just my x-cent).

```py
factory(Pet, adjust_require=lambda c, default: False if c.name == "pk" else default)
```

**Comment by podhmo** [comment]
```py
factory(Pet, adjust_require=lambda prop, default: False if prop.key == "pk" else default)
```

**Comment by podhmo** [comment]
implemented
