### ISSUE TITLE
All numeric types are reported as integer.

### ISSUE THREAD

**Issue by farshadhakimpour** [podhmo/alchemyjsonschema#36]
Hi, Do I use it wrong or it never reports a 'number' type in JSON schema? I get integer type for my numeric column types.

What I get:

{'properties': OrderedDict([('mmsi', {'type': 'integer'}),
                            ('basedatetime',
                             {'format': 'date-time', 'type': 'string'}),
                            ('lat', {'type': 'integer'}),
                            ('lon', {'type': 'integer'}),
                            ('sog', {'type': 'integer'}),
                            ('cog', {'type': 'integer'}),
                            ('heading', {'type': 'integer'}),
                            ('vesselname', {'maxLength': 32, 'type': 'string'}),
                            ('imo', {'maxLength': 16, 'type': 'string'}),
                            ('callsign', {'maxLength': 8, 'type': 'string'}),
                            ('vesseltype', {'type': 'integer'}),
                            ('status', {'type': 'integer'}),
                            ('length', {'type': 'integer'}),
                            ('width', {'type': 'integer'}),
                            ('draft', {'type': 'integer'}),
                            ('cargo', {'maxLength': 4, 'type': 'string'}),
                            ('transcieverclass',
                             {'maxLength': 2, 'type': 'string'})]),
 'required': ['mmsi', 'basedatetime'],
 'title': 'ais_feed',
 'type': 'object'}

What is created in the database:

CREATE TABLE IF NOT EXISTS ais_feed
(
    mmsi numeric(10,0) NOT NULL,
    basedatetime timestamp without time zone NOT NULL,
    lat numeric(7,5),
    lon numeric(8,5),
    sog numeric(4,1),
    cog numeric(4,1),
    heading numeric(4,1),
    vesselname character varying(32) COLLATE pg_catalog."default",
    imo character varying(16) COLLATE pg_catalog."default",
    callsign character varying(8) COLLATE pg_catalog."default",
    vesseltype smallint,
    status smallint,
    length numeric(4,1),
    width numeric(4,1),
    draft numeric(4,1),
    cargo character varying(4) COLLATE pg_catalog."default",
    transcieverclass character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT air_feed_pk PRIMARY KEY (mmsi, basedatetime)
)

**Comment by farshadhakimpour** [comment]
I believe line 50 of __init__ should change from t.Numeric: "integer",  to t.Numeric: "number",

**Comment by podhmo** [comment]
ah, yes. decimal is int, numeric is float （ignoring overflow）

**Comment by farshadhakimpour** [comment]
Hi again, Both decimal and numeric are number or float, unless the scale (number of digits after the decimal point) is zero (then integer):
numeric(p,s) or decimal(p,s)
