### ISSUE TITLE
Custom SQLA types

### ISSUE THREAD

**Issue by smahs** [podhmo/alchemyjsonschema#6]
For classes which are inherited from `sqlalchemy.types.TypeDecorator`.

For example, the following snippet for a `ChoiceType` class is persisted as `VARCHAR(1)`.
```python
class ChoiceType(TypeDecorator):
    impl = sqlalchemy.types.String(length=1)

    def __init__(self, choices, **kw):
        self.choices = dict(choices)
        super(ChoiceType, self).__init__(**kw)

    def process_bind_param(self, value, dialect):
        return [unicode(k) for k, v in self.choices.iteritems()
                if v == value][0]

    def process_result_value(self, value, dialect):
        return self.choices[value]
```

The parser throws an `InvalidStatus` exception:
```python
$ENV/lib/python2.7/site-packages/alchemyjsonschema/__init__.pyc in __getitem__(self, k)
    107             if issubclass(cls, type_):
    108                 return type_, self.mapping[type_]
--> 109         raise InvalidStatus("notfound: {k}".format(k=k))
    110
    111 DefaultClassfier = Classifier(default_column_to_schema)

InvalidStatus: notfound: VARCHAR(1) 
```

I believe, in this particular case of `VARCHAR(n)`, it should be converted to:
```json
{ 
    "type": "string",
    "maxLength": <<LENGTH>>,
}
```

**Comment by podhmo** [comment]
OK, if I have a time,  I will try to this issue.

**Comment by podhmo** [comment]
Normally, I only using `impl` attribute with class that want customizing.
But, If your customized type has default parameters, alchemygensonschema should be including it.

http://docs.sqlalchemy.org/en/latest/core/custom_types.html#sqlalchemy.types.TypeDecorator.__init__

> If the class level impl is not a callable (the unusual case), it will be assigned to the same instance attribute ‘as-is’, ignoring those arguments passed to the constructor.

**Comment by podhmo** [comment]
supported

**Comment by podhmo** [comment]
Thank you, supported and ver 0.2.3 is released.

**Comment by smahs** [comment]
Okay, thanks! I will test and post back.
